name: coffe_shop

description: "CoffeeModel - UTS project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/americano.jpeg
    - assets/images/capuccino.jpeg
    - assets/images/espresso.jpeg
    - assets/images/latte.jpeg
    - assets/images/lungo.jpeg
    - assets/images/macchiato.jpeg
    - assets/images/marketing.jpeg
    - assets/images/mocha.jpeg
    - assets/images/viena.jpeg
    - assets/images/propil.jpg
    - assets/images/jenis.jpg
    - assets/images/promo.jpg
    - assets/images/baground.png